### ISSUE TITLE
Cross-Origin Request Blocked when using a proxy

### ISSUE THREAD

**Issue by Wieke** [April93/Kaffiene#20]
Hi Everyone

So I've tried using the zite and it doesn't seem to work. I'm getting the following errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://zeronet.example.com/1Mr5rX9TauvaGReB4RjCaE6D37FJQaY5Ba/data.txt. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
NetworkError: A network error occurred.  1Mr5rX9TauvaGReB4RjCaE6D37FJQaY5Ba:61
TypeError: datau is undefined[Learn More]  1Mr5rX9TauvaGReB4RjCaE6D37FJQaY5Ba:487:1
TypeError: gup(...) is null[Learn More]  1Mr5rX9TauvaGReB4RjCaE6D37FJQaY5Ba:537:9
```

I suspect this has something to do with me running ZeroNet on a private proxy, though if I access the zite through a locally run zeronet I still get this error (but at least the zite seems to function):

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/data/ZeroWiki.db. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

Now I've seen errors like this when I was messing around a little with making own zite. As far as i understand it it has something to do with the limitations the sandboxed iframe imposes upon the zite. It is not allowed to refer back to the origin of the site (because the origin in most zeronet setups would be localhost). And if I stick a "allow-same-origin" (bad of me, I know) in the iframe sandbox attribute for a moment the problems go away. But the correct way of downloading a file from the zite, without running into this issue, is to use the [fileGet](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#fileget-inner_path-required-format-timeout) method of the zeroframe api.

Cheers,

Wieke

**Comment by April93** [comment]
I can't recreate this error. Can you please give specifics (and the proxy domain if public)? On the proxies I tested, [0netproxy.ml](https://0netproxy.ml/kaffiene.bit), [fuckcf](https://fuckcf.cf/kaffiene.bit), and [arukascloud](https://zero.arukascloud.io/kaffiene.bit/) all do not provide this error. Nor on my own local machine.

The only CORS error I get is on proxies, relating to grabbing the ZeroWiki db, which is expected. Given that I, nor the proxies, nor anyone else has had this problem, I have to assume it's a problem with your setup.  See the attached image:

![screen shot 2017-05-10 at 5 12 20 am](https://cloud.githubusercontent.com/assets/27911816/25898059/52122082-353f-11e7-8e58-1369af52664a.png)

And through a proxy:

![screen shot 2017-05-10 at 5 13 50 am](https://cloud.githubusercontent.com/assets/27911816/25898095/7cc148ee-353f-11e7-80f3-fe29c9442d5e.png)

**Comment by Wieke** [comment]
So while I trying to figure out some way to help reproduce the error I couldn't help but notice that you already fixed it. I guess I can confirm that commit 35d5f19659fadbd6bc76376236f7d021c9c02e2c fixed the issue for me.

Bit curious why other proxies didn't have the same issue. All I did was enable TOR and the UiPassword plugin then put the thing behind a nginx reverse proxy (with [this](https://github.com/April93/Kaffiene/files/997079/zeronet.txt) configuration). I wonder if it may have had something to do with the fact that both the proxy and the machine I used to access it were on the same LAN. (Which I assume wasn't the case when you tested it.)

Anyway thanks for fixing it so quickly (especially since you couldn't reproduce it).

**Comment by April93** [comment]
Yeah I have no idea what the issue was. It's worth noting that really only the Kaffiene index was really fixed. I can fix the untagged index, and zerome users indexes as well, but I didn't see it as a pressing issue. Maybe a bit later.

All I did was follow your suggestion of switching to the ZeroNet fileget method. Only issue is that I can't do this for other DB/index queries, such as for ZeroWiki, other search engines, etc. So those probably won't ever work with your setup unless ZeroNet adds cross-site file fetching. Either way, Kaffiene should at least work now for you, for basic site searching.

I'll see if I can switch the other indexes over soon. Might as well use best practices, even if I and any other user can't recreate this haha.
