### ISSUE TITLE
forked kaffie.bit and make a working protocol handler

### ISSUE THREAD

**Issue by Merith-TK** [April93/Kaffiene#21]
Okay so i forked your work from kaffie.bit, and made a `web+zero://` protocol handler because js has limits and dont allow `zero://` to be a valid handler.

it can be found [Here](http://127.0.0.1:43110/1JyMUCtShELPTKSF1HR3XUj4QEZx58Jcwy/)
and once setup, links like `web+zero://mail.zeronetwork.bit` will work. If you want me to add anything, let me know or z/email me at `merithtk@zeroid.bit` or `merith.tk@gmail.com`

**Comment by April93** [comment]
Not related to kaffiene. The idea behind having the zero:// protocol was to make a shorthand for zeronet links. but web+zero:// is too long so no one would really use it. http://zero/ still works though. I'd love to see proper link handling with zeronet, but it's development is pretty dead.
